spring.datasource.url=jdbc:postgresql://localhost:5432/Telegram_Bot_Notification
spring.datasource.username=Telegram_Bot_Notification
spring.datasource.password=telegram_bot_notification
telegram.bot.token=8323720064:AAGkfMr137Pze44z8HFuKEkyI45UUoLxXK4
spring.jpa.hibernate.ddl = update
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml