spring.datasource.url=jdbc:postgresql://localhost:5432/telegram-bot
spring.datasource.username=Telegram_bot
spring.datasource.password=telegram-bot
telegram.bot.token=8323720064:AAGkfMr137Pze44z8HFuKEkyI45UUoLxXK4
spring.liquibase.default-schema=public
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update
